#!/bin/sh

VERSTR="`git describe --long --tags --dirty --always`"

VER1="`echo $VERSTR | cut -d'-' -f1`"
VER2=$((`echo $VERSTR | cut -d'-' -f2` + 1))

VERSTR="__version__ = '${VER1}.${VER2}'"

echo "$VERSTR" > aprslib/version.py

git add aprslib/version.py
