name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'dev_requirements.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'dev_requirements.txt'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, pypy2, pypy3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Env
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          make init
      - name: Run Tests
        run: |
          make test
      - name: Upload to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: "${{ matrix.os }}_${{ matrix.python-version }}"
        run: |
          coveralls --service=github

  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Install coveralls
      run: |
        pip3 install --upgrade coveralls
    - name: Send coverage finish to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --finish
